import type { CompetencyCatalog, CompetencyDefinition } from "@/lib/competencies/contract";
import {
  COMPETENCY_CATALOG_CONTRACT_VERSION,
  COMPETENCY_CATALOG_VERSION
} from "@/lib/competencies/contract";

const competency = (definition: Omit<CompetencyDefinition, "version">): CompetencyDefinition => ({
  ...definition,
  version: COMPETENCY_CATALOG_VERSION
});

const competencies: CompetencyDefinition[] = [
  competency({
    id: "backend-service-development",
    name: "Backend Service Development",
    category: "BACKEND_ENGINEERING",
    description: "Professional implementation of backend services and server-side systems.",
    aliases: ["backend development", "backend services", "server-side development"],
    requirementSignals: ["backend", "server-side", "service development"],
    evidenceSignals: ["backend", "service", "api", "server-side"],
    technologySignals: ["Node.js", "Python", "Java", "Go", "C#", "Kotlin", "Spring Boot", "FastAPI", "Flask", "Express", "NestJS"],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["rest-api-design", "system-design"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["ownership", "delivery"],
    allowedRequirementKinds: ["TECHNOLOGY", "RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ROLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "rest-api-design",
    name: "REST API Design",
    category: "API_ENGINEERING",
    description: "Design and implementation of REST or RESTful APIs.",
    aliases: ["rest api", "restful design", "restful api", "api design"],
    requirementSignals: ["rest", "restful", "api design", "rest api"],
    evidenceSignals: ["api", "rest", "restful", "endpoint", "http service"],
    technologySignals: ["REST API", "FastAPI", "Flask", "Express", "NestJS", "Spring Boot", "API Gateway", "Lambda"],
    parentCompetencyIds: ["backend-service-development"],
    relatedCompetencyIds: ["api-integration", "graphql"],
    stronglyImpliedCompetencyIds: ["backend-service-development"],
    weaklyRelatedCompetencyIds: ["technical-communication"],
    allowedRequirementKinds: ["TECHNOLOGY", "RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "ARCHITECTURE_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "api-integration",
    name: "API Integration",
    category: "API_ENGINEERING",
    description: "Integrating APIs and services across internal or external systems.",
    aliases: ["api integration", "service integration", "system integration"],
    requirementSignals: ["integration", "integrate", "api integration"],
    evidenceSignals: ["integrated", "integration", "external systems", "internal platforms"],
    technologySignals: ["REST API", "GraphQL"],
    parentCompetencyIds: ["backend-service-development"],
    relatedCompetencyIds: ["external-system-integration", "messaging-and-queueing"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "TECHNOLOGY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "external-system-integration",
    name: "External-System Integration",
    category: "API_ENGINEERING",
    description: "Integration work spanning third-party systems, vendors, or partner platforms.",
    aliases: ["third-party integration", "external integrations", "partner integration"],
    requirementSignals: ["third-party", "external-system", "external systems", "partner systems"],
    evidenceSignals: ["third-party", "partner", "vendor", "external platform"],
    technologySignals: ["REST API", "GraphQL"],
    parentCompetencyIds: ["api-integration"],
    relatedCompetencyIds: ["api-integration"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "TECHNOLOGY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "graphql",
    name: "GraphQL",
    category: "API_ENGINEERING",
    description: "Implementation or design of GraphQL services.",
    aliases: ["graphql"],
    requirementSignals: ["graphql"],
    evidenceSignals: ["graphql"],
    technologySignals: ["GraphQL"],
    parentCompetencyIds: ["rest-api-design"],
    relatedCompetencyIds: ["backend-service-development"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["TECHNOLOGY", "RESPONSIBILITY", "ARCHITECTURE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "EXACT"
  }),
  competency({
    id: "event-driven-systems",
    name: "Event-Driven Systems",
    category: "BACKEND_ENGINEERING",
    description: "Design or operation of event-driven systems, messaging, and asynchronous flows.",
    aliases: ["event driven systems", "event-driven architecture"],
    requirementSignals: ["event-driven", "queue", "messaging", "asynchronous processing"],
    evidenceSignals: ["queue", "messaging", "async", "event-driven", "pubsub"],
    technologySignals: ["Event-Driven Systems", "Kafka", "SQS", "SNS", "RabbitMQ", "NServiceBus", "Lambda"],
    parentCompetencyIds: ["backend-service-development"],
    relatedCompetencyIds: ["messaging-and-queueing", "asynchronous-processing"],
    stronglyImpliedCompetencyIds: ["messaging-and-queueing"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["TECHNOLOGY", "ARCHITECTURE", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "ARCHITECTURE_EXAMPLE", "PROJECT_ARCHITECTURE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "messaging-and-queueing",
    name: "Messaging and Queueing",
    category: "BACKEND_ENGINEERING",
    description: "Implementation of queue-based or messaging-based integrations.",
    aliases: ["messaging", "queueing", "message queues"],
    requirementSignals: ["queues", "messaging", "pubsub"],
    evidenceSignals: ["queue", "messaging", "events"],
    technologySignals: ["Kafka", "SQS", "SNS", "RabbitMQ", "NServiceBus"],
    parentCompetencyIds: ["event-driven-systems"],
    relatedCompetencyIds: ["event-driven-systems"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["TECHNOLOGY", "RESPONSIBILITY", "ARCHITECTURE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "system-design",
    name: "System Design",
    category: "SYSTEM_DESIGN",
    description: "Design of systems, services, and technical architecture.",
    aliases: ["system design", "architecture"],
    requirementSignals: ["system design", "architecture", "architect"],
    evidenceSignals: ["architecture", "designed systems", "system design"],
    technologySignals: ["Distributed Systems", "Microservices"],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["distributed-systems", "scalability", "maintainability"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["architecture-influence"],
    allowedRequirementKinds: ["ARCHITECTURE", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["ARCHITECTURE_EXAMPLE", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "distributed-systems",
    name: "Distributed Systems",
    category: "DISTRIBUTED_SYSTEMS",
    description: "Design or operation of distributed services and processing.",
    aliases: ["distributed systems", "distributed processing"],
    requirementSignals: ["distributed systems", "distributed"],
    evidenceSignals: ["distributed", "scalability", "service boundaries"],
    technologySignals: ["Distributed Systems", "Microservices", "Kafka", "Lambda"],
    parentCompetencyIds: ["system-design"],
    relatedCompetencyIds: ["scalability", "performance-engineering", "reliability-engineering"],
    stronglyImpliedCompetencyIds: ["system-design"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["ARCHITECTURE", "TECHNOLOGY", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["ARCHITECTURE_EXAMPLE", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "performance-engineering",
    name: "Performance Engineering",
    category: "PERFORMANCE",
    description: "Improving throughput, latency, scalability, or resource efficiency.",
    aliases: ["performance engineering", "performance", "optimization"],
    requirementSignals: ["performance", "throughput", "latency", "optimization", "low-latency", "high-throughput"],
    evidenceSignals: ["performance", "throughput", "latency", "optimized", "optimization"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["throughput-optimization", "latency-reduction", "scalability", "resource-optimization", "database-optimization"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["distributed-systems"],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE", "OTHER"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_METRIC", "PROFESSIONAL_RESPONSIBILITY", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "throughput-optimization",
    name: "Throughput Optimization",
    category: "PERFORMANCE",
    description: "Improving throughput or processing volume.",
    aliases: ["throughput optimization", "throughput", "scale throughput"],
    requirementSignals: ["throughput", "high-throughput"],
    evidenceSignals: ["throughput", "scale", "2x", "improved processing"],
    technologySignals: [],
    parentCompetencyIds: ["performance-engineering"],
    relatedCompetencyIds: ["parallel-processing", "resource-optimization"],
    stronglyImpliedCompetencyIds: ["performance-engineering"],
    weaklyRelatedCompetencyIds: ["latency-reduction"],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE", "OTHER"],
    preferredEvidenceFamilies: ["PROFESSIONAL_METRIC", "PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "latency-reduction",
    name: "Latency Reduction",
    category: "PERFORMANCE",
    description: "Improving latency or response-time behavior.",
    aliases: ["low latency", "latency reduction", "response time"],
    requirementSignals: ["low-latency", "latency", "response time"],
    evidenceSignals: ["latency", "response time"],
    technologySignals: [],
    parentCompetencyIds: ["performance-engineering"],
    relatedCompetencyIds: ["throughput-optimization"],
    stronglyImpliedCompetencyIds: ["performance-engineering"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE", "OTHER"],
    preferredEvidenceFamilies: ["PROFESSIONAL_METRIC", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "parallel-processing",
    name: "Parallel Processing",
    category: "PERFORMANCE",
    description: "Parallel or concurrent processing for scale or performance.",
    aliases: ["parallel processing", "concurrent processing"],
    requirementSignals: ["parallel processing", "parallel", "concurrent"],
    evidenceSignals: ["parallel", "concurrent", "multi-threaded", "multi threaded"],
    technologySignals: [],
    parentCompetencyIds: ["performance-engineering"],
    relatedCompetencyIds: ["throughput-optimization", "asynchronous-processing"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "asynchronous-processing",
    name: "Asynchronous Processing",
    category: "PERFORMANCE",
    description: "Async or non-blocking workflows used for scale or delivery.",
    aliases: ["asynchronous processing", "async processing", "asynchronous workflows"],
    requirementSignals: ["asynchronous", "async"],
    evidenceSignals: ["async", "asynchronous", "non-blocking"],
    technologySignals: ["SQS", "SNS", "Kafka", "RabbitMQ", "Lambda"],
    parentCompetencyIds: ["event-driven-systems"],
    relatedCompetencyIds: ["parallel-processing", "throughput-optimization"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "TECHNOLOGY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "database-optimization",
    name: "Database Optimization",
    category: "PERFORMANCE",
    description: "Improving database performance, query shape, storage, or scaling.",
    aliases: ["database optimization", "query optimization"],
    requirementSignals: ["database optimization", "query performance", "sql performance"],
    evidenceSignals: ["query optimization", "database performance", "postgres tuning"],
    technologySignals: ["PostgreSQL", "SQL Server", "MySQL", "BigQuery", "Snowflake"],
    parentCompetencyIds: ["performance-engineering"],
    relatedCompetencyIds: ["relational-databases", "postgresql"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "TECHNOLOGY", "EXPERIENCE", "DATA"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_METRIC", "PROFESSIONAL_RESPONSIBILITY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "resource-optimization",
    name: "Resource Optimization",
    category: "PERFORMANCE",
    description: "Improving efficiency of compute, storage, or infrastructure use.",
    aliases: ["resource optimization", "efficiency optimization"],
    requirementSignals: ["resource optimization", "efficiency"],
    evidenceSignals: ["optimized", "efficiency", "cost reduction"],
    technologySignals: ["AWS", "Azure", "GCP"],
    parentCompetencyIds: ["performance-engineering"],
    relatedCompetencyIds: ["cloud-engineering", "deployment-engineering"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_METRIC"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "SUPPORTING"
  }),
  competency({
    id: "scalability",
    name: "Scalability",
    category: "DISTRIBUTED_SYSTEMS",
    description: "Building or improving systems for scale.",
    aliases: ["scalability", "scale systems"],
    requirementSignals: ["scalability", "scale"],
    evidenceSignals: ["scale", "scaled", "throughput"],
    technologySignals: ["Distributed Systems", "Microservices"],
    parentCompetencyIds: ["system-design"],
    relatedCompetencyIds: ["distributed-systems", "performance-engineering"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["ARCHITECTURE", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "ARCHITECTURE_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "high-availability",
    name: "High Availability",
    category: "RELIABILITY",
    description: "Systems designed for strong availability characteristics.",
    aliases: ["high availability", "high-availability"],
    requirementSignals: ["high availability", "high-availability"],
    evidenceSignals: ["high availability", "availability", "resilient services"],
    technologySignals: [],
    parentCompetencyIds: ["reliability-engineering"],
    relatedCompetencyIds: ["fault-tolerance", "zero-downtime-delivery"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["ARCHITECTURE", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PRODUCTION_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "fault-tolerance",
    name: "Fault Tolerance",
    category: "RELIABILITY",
    description: "Tolerance of failures or degraded components.",
    aliases: ["fault tolerance", "fault-tolerant", "fault tolerant"],
    requirementSignals: ["fault tolerance", "fault tolerant"],
    evidenceSignals: ["fault tolerant", "resilience", "graceful degradation"],
    technologySignals: [],
    parentCompetencyIds: ["reliability-engineering"],
    relatedCompetencyIds: ["high-availability"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["ARCHITECTURE", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "ARCHITECTURE_EXAMPLE", "PRODUCTION_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "production-support",
    name: "Production Support",
    category: "RELIABILITY",
    description: "Direct operation or support of production systems.",
    aliases: ["production support", "production operations"],
    requirementSignals: ["production support", "production operations"],
    evidenceSignals: ["production", "incident response", "operated systems"],
    technologySignals: [],
    parentCompetencyIds: ["reliability-engineering"],
    relatedCompetencyIds: ["observability", "release-reliability"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "EXPERIENCE", "OTHER"],
    preferredEvidenceFamilies: ["PRODUCTION_EXAMPLE", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "reliability-engineering",
    name: "Reliability Engineering",
    category: "RELIABILITY",
    description: "Reliability, resilience, production health, and operational correctness.",
    aliases: ["reliability", "resilience"],
    requirementSignals: ["reliability", "resilience", "fault tolerance", "production reliability"],
    evidenceSignals: ["reliability", "resilience", "fault tolerant", "incident"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["high-availability", "fault-tolerance", "observability", "production-support", "zero-downtime-delivery"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["ci-cd"],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE", "OTHER"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PRODUCTION_EXAMPLE", "PROFESSIONAL_RESPONSIBILITY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "maintainability",
    name: "Maintainability",
    category: "RELIABILITY",
    description: "Maintainable systems, code, and operational practices.",
    aliases: ["maintainability", "maintainable"],
    requirementSignals: ["maintainable", "maintainability"],
    evidenceSignals: ["maintainable", "improved maintainability", "refactoring", "simplified operations"],
    technologySignals: [],
    parentCompetencyIds: ["reliability-engineering"],
    relatedCompetencyIds: ["system-design", "documentation-practices", "continuous-improvement"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE", "OTHER"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "ARCHITECTURE_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "observability",
    name: "Observability",
    category: "RELIABILITY",
    description: "Monitoring, logging, instrumentation, and operational visibility.",
    aliases: ["observability", "monitoring", "logging", "instrumentation"],
    requirementSignals: ["observability", "monitoring", "logging"],
    evidenceSignals: ["monitoring", "logging", "instrumentation", "alerts"],
    technologySignals: ["CloudWatch"],
    parentCompetencyIds: ["reliability-engineering"],
    relatedCompetencyIds: ["production-support"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT", "PRODUCTION_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "zero-downtime-delivery",
    name: "Zero-Downtime Delivery",
    category: "DELIVERY_AND_OPERATIONS",
    description: "Delivery practices aimed at safe, uninterrupted releases.",
    aliases: ["zero-downtime delivery", "zero downtime", "safe releases"],
    requirementSignals: ["zero-downtime", "zero downtime", "safe delivery"],
    evidenceSignals: ["safe deployment", "rolling deploy", "release reliability"],
    technologySignals: ["CI/CD", "Docker", "Kubernetes"],
    parentCompetencyIds: ["deployment-engineering"],
    relatedCompetencyIds: ["ci-cd", "release-reliability", "reliability-engineering"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "ARCHITECTURE", "EXPERIENCE", "OTHER"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PRODUCTION_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "SUPPORTING"
  }),
  competency({
    id: "software-testing",
    name: "Software Testing",
    category: "TESTING_AND_QUALITY",
    description: "Testing strategy and implementation.",
    aliases: ["testing", "software testing", "testing strategy"],
    requirementSignals: ["testing", "test strategy", "quality"],
    evidenceSignals: ["testing", "tests", "quality"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["automated-testing", "testability", "ci-cd"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "OTHER", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT", "PRODUCTION_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "automated-testing",
    name: "Automated Testing",
    category: "TESTING_AND_QUALITY",
    description: "Automated test suites or automated quality checks.",
    aliases: ["automated testing", "test automation"],
    requirementSignals: ["automated testing", "test automation"],
    evidenceSignals: ["automated tests", "test automation", "integration tests"],
    technologySignals: ["CI/CD"],
    parentCompetencyIds: ["software-testing"],
    relatedCompetencyIds: ["ci-cd", "testability"],
    stronglyImpliedCompetencyIds: ["software-testing"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "OTHER", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "test-driven-development",
    name: "Test-Driven Development",
    category: "TESTING_AND_QUALITY",
    description: "Explicit TDD practice.",
    aliases: ["tdd", "test-driven development"],
    requirementSignals: ["tdd", "test-driven development"],
    evidenceSignals: ["tdd", "test-driven development"],
    technologySignals: [],
    parentCompetencyIds: ["software-testing"],
    relatedCompetencyIds: ["testability"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "EXACT"
  }),
  competency({
    id: "testability",
    name: "Testability",
    category: "TESTING_AND_QUALITY",
    description: "Writing testable, verifiable code and workflows.",
    aliases: ["testability", "testable code", "testable"],
    requirementSignals: ["testable", "testability"],
    evidenceSignals: ["testable", "designed for testing", "validation"],
    technologySignals: [],
    parentCompetencyIds: ["software-testing"],
    relatedCompetencyIds: ["validation", "automated-testing"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "validation",
    name: "Validation",
    category: "TESTING_AND_QUALITY",
    description: "Validation of workflows, systems, or inputs.",
    aliases: ["validation", "validate"],
    requirementSignals: ["validation", "validate"],
    evidenceSignals: ["validation", "validate"],
    technologySignals: [],
    parentCompetencyIds: ["software-testing"],
    relatedCompetencyIds: ["testability", "prompt-and-workflow-validation"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "ci-cd",
    name: "CI/CD",
    category: "DELIVERY_AND_OPERATIONS",
    description: "Continuous integration and delivery practices.",
    aliases: ["ci/cd", "continuous integration", "continuous delivery"],
    requirementSignals: ["ci/cd", "continuous integration", "continuous delivery"],
    evidenceSignals: ["ci/cd", "deployment", "delivery pipeline", "build pipeline"],
    technologySignals: ["CI/CD", "Jenkins", "Azure DevOps", "CloudFormation", "Terraform"],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["deployment-engineering", "release-reliability", "zero-downtime-delivery"],
    stronglyImpliedCompetencyIds: ["release-reliability"],
    weaklyRelatedCompetencyIds: ["software-testing"],
    allowedRequirementKinds: ["RESPONSIBILITY", "TECHNOLOGY", "EXPERIENCE", "OTHER"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT", "PRODUCTION_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "deployment-engineering",
    name: "Deployment Engineering",
    category: "DELIVERY_AND_OPERATIONS",
    description: "Engineering delivery, deployment, and release workflows.",
    aliases: ["deployment engineering", "deployment", "release engineering"],
    requirementSignals: ["deployment", "release engineering", "shipping"],
    evidenceSignals: ["deployment", "release", "shipping"],
    technologySignals: ["CI/CD", "Docker", "Kubernetes", "Lambda"],
    parentCompetencyIds: ["ci-cd"],
    relatedCompetencyIds: ["release-reliability", "zero-downtime-delivery"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "OTHER", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT", "PRODUCTION_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "release-reliability",
    name: "Release Reliability",
    category: "DELIVERY_AND_OPERATIONS",
    description: "Safe and dependable release processes.",
    aliases: ["release reliability", "reliable releases"],
    requirementSignals: ["release reliability", "safe releases"],
    evidenceSignals: ["safe release", "rollback", "deployment safety"],
    technologySignals: ["CI/CD", "Docker", "Kubernetes"],
    parentCompetencyIds: ["deployment-engineering"],
    relatedCompetencyIds: ["zero-downtime-delivery", "reliability-engineering"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["RESPONSIBILITY", "OTHER", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PRODUCTION_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "SUPPORTING"
  }),
  competency({
    id: "documentation-practices",
    name: "Documentation Practices",
    category: "COMMUNICATION",
    description: "Clear written documentation, runbooks, or design artifacts.",
    aliases: ["documentation", "written communication", "runbooks"],
    requirementSignals: ["documentation", "written"],
    evidenceSignals: ["documentation", "documented", "runbook"],
    technologySignals: [],
    parentCompetencyIds: ["technical-communication"],
    relatedCompetencyIds: ["knowledge-sharing"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["COMMUNICATION", "OTHER", "RESPONSIBILITY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ACCOMPLISHMENT", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "cloud-engineering",
    name: "Cloud Engineering",
    category: "CLOUD_AND_INFRASTRUCTURE",
    description: "Engineering systems on cloud platforms.",
    aliases: ["cloud engineering", "cloud architecture"],
    requirementSignals: ["cloud", "cloud platform"],
    evidenceSignals: ["aws", "azure", "gcp", "cloud"],
    technologySignals: ["AWS", "Azure", "GCP", "Lambda", "ECS", "EKS", "S3"],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["aws", "azure", "gcp"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["TECHNOLOGY", "CLOUD", "ARCHITECTURE", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ROLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "aws",
    name: "AWS",
    category: "CLOUD_AND_INFRASTRUCTURE",
    description: "Implementation experience on AWS.",
    aliases: ["aws", "amazon web services"],
    requirementSignals: ["aws", "amazon web services"],
    evidenceSignals: ["aws", "lambda", "sqs", "sns", "ecs", "eks", "cloudwatch", "s3"],
    technologySignals: ["AWS", "Lambda", "SQS", "SNS", "ECS", "EKS", "CloudWatch", "S3"],
    parentCompetencyIds: ["cloud-engineering"],
    relatedCompetencyIds: ["event-driven-systems", "deployment-engineering"],
    stronglyImpliedCompetencyIds: ["cloud-engineering"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["TECHNOLOGY", "CLOUD", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ROLE", "ACTIVE_CERTIFICATION"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "EXACT"
  }),
  competency({
    id: "azure",
    name: "Azure",
    category: "CLOUD_AND_INFRASTRUCTURE",
    description: "Implementation experience on Azure.",
    aliases: ["azure", "microsoft azure"],
    requirementSignals: ["azure", "microsoft azure"],
    evidenceSignals: ["azure"],
    technologySignals: ["Azure", "Azure DevOps"],
    parentCompetencyIds: ["cloud-engineering"],
    relatedCompetencyIds: [],
    stronglyImpliedCompetencyIds: ["cloud-engineering"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["TECHNOLOGY", "CLOUD", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ROLE", "ACTIVE_CERTIFICATION"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "EXACT"
  }),
  competency({
    id: "gcp",
    name: "GCP",
    category: "CLOUD_AND_INFRASTRUCTURE",
    description: "Implementation experience on GCP.",
    aliases: ["gcp", "google cloud", "google cloud platform"],
    requirementSignals: ["gcp", "google cloud"],
    evidenceSignals: ["gcp", "google cloud"],
    technologySignals: ["GCP"],
    parentCompetencyIds: ["cloud-engineering"],
    relatedCompetencyIds: [],
    stronglyImpliedCompetencyIds: ["cloud-engineering"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["TECHNOLOGY", "CLOUD", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ROLE", "ACTIVE_CERTIFICATION"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "EXACT"
  }),
  competency({
    id: "relational-databases",
    name: "Relational Databases",
    category: "DATA_AND_STORAGE",
    description: "Use or design of relational databases and SQL data stores.",
    aliases: ["relational databases", "sql", "database systems"],
    requirementSignals: ["sql", "database", "relational"],
    evidenceSignals: ["sql", "postgres", "database"],
    technologySignals: ["PostgreSQL", "MySQL", "SQL Server"],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["postgresql", "data-pipelines", "database-optimization"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["TECHNOLOGY", "DATA", "EXPERIENCE", "RESPONSIBILITY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ROLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "postgresql",
    name: "PostgreSQL",
    category: "DATA_AND_STORAGE",
    description: "Implementation experience with PostgreSQL.",
    aliases: ["postgresql", "postgres"],
    requirementSignals: ["postgres", "postgresql"],
    evidenceSignals: ["postgres", "postgresql"],
    technologySignals: ["PostgreSQL"],
    parentCompetencyIds: ["relational-databases"],
    relatedCompetencyIds: ["database-optimization"],
    stronglyImpliedCompetencyIds: ["relational-databases"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["TECHNOLOGY", "DATA", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROFESSIONAL_ROLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "EXACT"
  }),
  competency({
    id: "streaming-data",
    name: "Streaming Data",
    category: "DATA_AND_STORAGE",
    description: "Streaming or event-based data processing.",
    aliases: ["streaming data", "stream processing"],
    requirementSignals: ["streaming", "stream processing"],
    evidenceSignals: ["streaming", "event streams", "kafka"],
    technologySignals: ["Kafka", "Debezium"],
    parentCompetencyIds: ["data-pipelines"],
    relatedCompetencyIds: ["event-driven-systems"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["DATA", "RESPONSIBILITY", "EXPERIENCE", "TECHNOLOGY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "data-pipelines",
    name: "Data Pipelines",
    category: "DATA_AND_STORAGE",
    description: "Construction or support of data processing pipelines.",
    aliases: ["data pipelines", "etl", "data processing"],
    requirementSignals: ["data pipelines", "data processing", "etl"],
    evidenceSignals: ["pipeline", "etl", "ingestion", "data processing"],
    technologySignals: ["BigQuery", "Snowflake", "Kafka", "Debezium"],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["data-ingestion", "streaming-data", "search-and-retrieval"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["DATA", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "data-ingestion",
    name: "Data Ingestion",
    category: "DATA_AND_STORAGE",
    description: "Ingestion of documents, records, or datasets.",
    aliases: ["data ingestion", "document ingestion", "ingestion"],
    requirementSignals: ["ingestion", "document ingestion"],
    evidenceSignals: ["ingestion", "document processing", "document workflows"],
    technologySignals: [],
    parentCompetencyIds: ["data-pipelines"],
    relatedCompetencyIds: ["document-understanding", "search-and-retrieval"],
    stronglyImpliedCompetencyIds: ["data-pipelines"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["DATA", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT", "ARCHITECTURE_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "search-and-retrieval",
    name: "Search and Retrieval",
    category: "AI_AND_SEARCH",
    description: "Search, retrieval, retrieval workflows, or retrieval systems.",
    aliases: ["search and retrieval", "semantic retrieval", "retrieval", "search"],
    requirementSignals: ["retrieval", "search", "semantic retrieval"],
    evidenceSignals: ["retrieval", "search", "semantic search", "knowledge search"],
    technologySignals: ["RAG"],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["semantic-search", "rag", "document-understanding"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["data-ingestion"],
    allowedRequirementKinds: ["DATA", "AI_ML", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "ARCHITECTURE_EXAMPLE", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "semantic-search",
    name: "Semantic Search",
    category: "AI_AND_SEARCH",
    description: "Semantic-search systems or workflows.",
    aliases: ["semantic search", "ai-powered search", "ai powered search"],
    requirementSignals: ["semantic search", "ai-powered search"],
    evidenceSignals: ["semantic search", "knowledge search", "retrieval"],
    technologySignals: ["RAG", "LLM", "OpenAI"],
    parentCompetencyIds: ["search-and-retrieval"],
    relatedCompetencyIds: ["rag", "llm-application-engineering"],
    stronglyImpliedCompetencyIds: ["search-and-retrieval"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["AI_ML", "DATA", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["ARCHITECTURE_EXAMPLE", "PROJECT_ACCOMPLISHMENT", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "vector-search",
    name: "Vector Search",
    category: "AI_AND_SEARCH",
    description: "Vector-search implementation or operation.",
    aliases: ["vector search"],
    requirementSignals: ["vector search"],
    evidenceSignals: ["vector search"],
    technologySignals: ["Qdrant", "pgvector", "ChromaDB"],
    parentCompetencyIds: ["search-and-retrieval"],
    relatedCompetencyIds: ["semantic-search"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["AI_ML", "DATA", "TECHNOLOGY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT", "ARCHITECTURE_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "EXACT"
  }),
  competency({
    id: "llm-application-engineering",
    name: "LLM Application Engineering",
    category: "AI_AND_SEARCH",
    description: "Building applications that use LLMs.",
    aliases: ["llm application engineering", "llm applications"],
    requirementSignals: ["llm", "large language model"],
    evidenceSignals: ["llm", "openai", "ai workflow"],
    technologySignals: ["LLM", "OpenAI", "LangChain"],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["agentic-workflows", "rag"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["AI_ML", "TECHNOLOGY", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT", "ARCHITECTURE_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "agentic-workflows",
    name: "Agentic Workflows",
    category: "AI_AND_SEARCH",
    description: "Orchestration of tools or agents to complete workflows.",
    aliases: ["agentic workflows", "agents", "tool execution"],
    requirementSignals: ["agentic", "agents", "tool execution"],
    evidenceSignals: ["agents", "orchestration", "tool invocation", "tool execution"],
    technologySignals: ["LangChain", "OpenAI"],
    parentCompetencyIds: ["llm-application-engineering"],
    relatedCompetencyIds: ["prompt-and-workflow-validation"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["AI_ML", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT", "ARCHITECTURE_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "rag",
    name: "Retrieval-Augmented Generation",
    category: "AI_AND_SEARCH",
    description: "RAG workflows combining search and generation.",
    aliases: ["rag", "retrieval augmented generation"],
    requirementSignals: ["rag", "retrieval augmented generation"],
    evidenceSignals: ["rag", "retrieval augmented generation"],
    technologySignals: ["RAG"],
    parentCompetencyIds: ["search-and-retrieval"],
    relatedCompetencyIds: ["semantic-search", "llm-application-engineering"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["AI_ML", "DATA", "TECHNOLOGY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "EXACT"
  }),
  competency({
    id: "document-understanding",
    name: "Document Understanding",
    category: "AI_AND_SEARCH",
    description: "Processing or understanding document-heavy workflows.",
    aliases: ["document understanding", "document processing", "document workflows"],
    requirementSignals: ["document understanding", "document processing", "document ingestion"],
    evidenceSignals: ["document workflows", "document processing", "document-heavy"],
    technologySignals: [],
    parentCompetencyIds: ["data-ingestion"],
    relatedCompetencyIds: ["search-and-retrieval"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["AI_ML", "DATA", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT", "ARCHITECTURE_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "prompt-and-workflow-validation",
    name: "Prompt and Workflow Validation",
    category: "AI_AND_SEARCH",
    description: "Validation of AI prompts or workflow correctness.",
    aliases: ["prompt validation", "workflow validation"],
    requirementSignals: ["prompt validation", "workflow validation"],
    evidenceSignals: ["validation", "prompt", "workflow correctness"],
    technologySignals: ["LLM", "OpenAI"],
    parentCompetencyIds: ["validation"],
    relatedCompetencyIds: ["agentic-workflows"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["AI_ML", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "SUPPORTING"
  }),
  competency({
    id: "problem-solving",
    name: "Problem Solving",
    category: "OWNERSHIP_AND_EXECUTION",
    description: "Diagnosing and solving practical technical problems.",
    aliases: ["problem solving", "problem-solving"],
    requirementSignals: ["problem solving", "solve problems"],
    evidenceSignals: ["solved", "resolved", "troubleshot", "unblocked"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["technical-judgment", "continuous-improvement"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "ownership",
    name: "Ownership",
    category: "OWNERSHIP_AND_EXECUTION",
    description: "Taking responsibility for outcomes and delivery.",
    aliases: ["ownership", "own outcomes", "owning"],
    requirementSignals: ["ownership", "own"],
    evidenceSignals: ["ownership", "owned", "drove", "led end-to-end"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["independent-execution", "delivery", "continuous-improvement"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["problem-solving"],
    allowedRequirementKinds: ["RESPONSIBILITY", "LEADERSHIP", "OTHER", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY", "LEADERSHIP_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "independent-execution",
    name: "Independent Execution",
    category: "OWNERSHIP_AND_EXECUTION",
    description: "Hands-on execution with low oversight.",
    aliases: ["independent execution", "self-directed", "self directed"],
    requirementSignals: ["independent", "self-directed", "fast-paced"],
    evidenceSignals: ["independently", "self-directed", "drove end-to-end"],
    technologySignals: [],
    parentCompetencyIds: ["ownership"],
    relatedCompetencyIds: ["hands-on-engineering", "adaptability"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "continuous-improvement",
    name: "Continuous Improvement",
    category: "OWNERSHIP_AND_EXECUTION",
    description: "Improving systems, workflows, or delivery iteratively.",
    aliases: ["continuous improvement", "improvement", "improve"],
    requirementSignals: ["continuous improvement", "improve", "iteration"],
    evidenceSignals: ["improved", "optimization", "workflow improvements", "iterated"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["ownership", "problem-solving", "maintainability"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "adaptability",
    name: "Adaptability",
    category: "LEARNING_AND_ADAPTABILITY",
    description: "Adaptability across changing tools, contexts, or work.",
    aliases: ["adaptability", "adaptable", "flexibility"],
    requirementSignals: ["adaptability", "adaptable", "fast learner"],
    evidenceSignals: ["adapted", "transitioned", "learned quickly", "fast learner"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["learning-agility", "hands-on-engineering"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["INTERVIEW_STORY", "PROFESSIONAL_ACCOMPLISHMENT", "PROJECT_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "learning-agility",
    name: "Learning Agility",
    category: "LEARNING_AND_ADAPTABILITY",
    description: "Evidence of quick learning and successful transitions.",
    aliases: ["learning agility", "fast learner", "learn quickly"],
    requirementSignals: ["fast learner", "learn quickly"],
    evidenceSignals: ["learned quickly", "ramped", "transitioned successfully"],
    technologySignals: [],
    parentCompetencyIds: ["adaptability"],
    relatedCompetencyIds: [],
    stronglyImpliedCompetencyIds: ["adaptability"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["INTERVIEW_STORY", "PROFESSIONAL_ACCOMPLISHMENT"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "hands-on-engineering",
    name: "Hands-On Engineering",
    category: "OWNERSHIP_AND_EXECUTION",
    description: "Direct implementation and practical execution.",
    aliases: ["hands-on engineering", "hands-on execution", "hands on"],
    requirementSignals: ["hands-on", "hands on"],
    evidenceSignals: ["built", "implemented", "shipped", "coded"],
    technologySignals: [],
    parentCompetencyIds: ["independent-execution"],
    relatedCompetencyIds: ["delivery"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "delivery",
    name: "Delivery",
    category: "OWNERSHIP_AND_EXECUTION",
    description: "Sustained delivery of working systems and outcomes.",
    aliases: ["delivery", "execution", "shipping"],
    requirementSignals: ["delivery", "ship", "execute"],
    evidenceSignals: ["delivered", "shipped", "released"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["ownership", "hands-on-engineering"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "business-outcome-orientation",
    name: "Business Outcome Orientation",
    category: "PRODUCT_AND_BUSINESS",
    description: "Connecting engineering work to business or user outcomes.",
    aliases: ["business outcomes", "customer impact", "business impact"],
    requirementSignals: ["business outcomes", "customer impact", "business impact"],
    evidenceSignals: ["business impact", "customer impact", "operational impact"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["product-collaboration", "technical-judgment"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "EXPERIENCE", "DOMAIN"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_METRIC", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "technical-judgment",
    name: "Technical Judgment",
    category: "PRODUCT_AND_BUSINESS",
    description: "Tradeoff-aware technical decisions.",
    aliases: ["technical judgment", "tradeoff analysis", "tradeoffs"],
    requirementSignals: ["tradeoff", "technical judgment"],
    evidenceSignals: ["tradeoff", "decision", "risk"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["architecture-influence", "risk-communication"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["OTHER", "RESPONSIBILITY", "LEADERSHIP", "EXPERIENCE"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "INTERVIEW_STORY", "LEADERSHIP_EXAMPLE"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "cross-functional-collaboration",
    name: "Cross-Functional Collaboration",
    category: "COLLABORATION",
    description: "Working across engineering and partner functions.",
    aliases: ["cross-functional collaboration", "cross functional collaboration", "team collaboration"],
    requirementSignals: ["cross-functional", "collaborate", "collaboration"],
    evidenceSignals: ["cross-functional", "collaborated", "stakeholders", "teams"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["stakeholder-collaboration", "product-collaboration", "technical-communication"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["mentoring"],
    allowedRequirementKinds: ["COLLABORATION", "COMMUNICATION", "RESPONSIBILITY", "LEADERSHIP"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "LEADERSHIP_EXAMPLE", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "stakeholder-collaboration",
    name: "Stakeholder Collaboration",
    category: "COLLABORATION",
    description: "Working with stakeholders outside the core engineering team.",
    aliases: ["stakeholder collaboration", "stakeholder management"],
    requirementSignals: ["stakeholder", "partner teams"],
    evidenceSignals: ["stakeholder", "partner", "business partners"],
    technologySignals: [],
    parentCompetencyIds: ["cross-functional-collaboration"],
    relatedCompetencyIds: ["risk-communication", "product-collaboration"],
    stronglyImpliedCompetencyIds: ["cross-functional-collaboration"],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["COLLABORATION", "COMMUNICATION", "RESPONSIBILITY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "product-collaboration",
    name: "Product Collaboration",
    category: "COLLABORATION",
    description: "Direct collaboration with product roles or product direction.",
    aliases: ["product collaboration", "work with product", "product partnership"],
    requirementSignals: ["product", "product teams"],
    evidenceSignals: ["product", "pm", "product management"],
    technologySignals: [],
    parentCompetencyIds: ["cross-functional-collaboration"],
    relatedCompetencyIds: ["business-outcome-orientation"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["stakeholder-collaboration"],
    allowedRequirementKinds: ["COLLABORATION", "COMMUNICATION", "RESPONSIBILITY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "technical-communication",
    name: "Technical Communication",
    category: "COMMUNICATION",
    description: "Clear technical communication across teams and stakeholders.",
    aliases: ["technical communication", "clear communication", "communicate clearly"],
    requirementSignals: ["communication", "communicate", "clear communication"],
    evidenceSignals: ["communicated", "shared updates", "presented", "documented"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["risk-communication", "documentation-practices", "cross-functional-collaboration"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["knowledge-sharing"],
    allowedRequirementKinds: ["COMMUNICATION", "RESPONSIBILITY", "COLLABORATION", "OTHER"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY", "LEADERSHIP_EXAMPLE"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "risk-communication",
    name: "Risk Communication",
    category: "COMMUNICATION",
    description: "Communicating risk, tradeoffs, and decisions.",
    aliases: ["risk communication", "communicating risks", "decision communication"],
    requirementSignals: ["risk updates", "risks", "tradeoffs"],
    evidenceSignals: ["risks", "tradeoffs", "decisions", "status updates"],
    technologySignals: [],
    parentCompetencyIds: ["technical-communication"],
    relatedCompetencyIds: ["technical-judgment", "stakeholder-collaboration"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["COMMUNICATION", "RESPONSIBILITY", "COLLABORATION", "OTHER"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "mentoring",
    name: "Mentoring",
    category: "LEADERSHIP",
    description: "Mentoring or coaching engineers.",
    aliases: ["mentoring", "mentor", "coaching"],
    requirementSignals: ["mentor", "mentoring", "coach"],
    evidenceSignals: ["mentored", "mentoring", "coached"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["knowledge-sharing", "technical-leadership"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["cross-functional-collaboration"],
    allowedRequirementKinds: ["LEADERSHIP", "COLLABORATION", "RESPONSIBILITY", "OTHER"],
    preferredEvidenceFamilies: ["LEADERSHIP_EXAMPLE", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "knowledge-sharing",
    name: "Knowledge Sharing",
    category: "LEADERSHIP",
    description: "Sharing knowledge, onboarding, or internal education.",
    aliases: ["knowledge sharing", "enablement", "documentation practices"],
    requirementSignals: ["knowledge sharing", "onboarding", "enable others"],
    evidenceSignals: ["knowledge sharing", "onboarded", "documentation"],
    technologySignals: [],
    parentCompetencyIds: ["mentoring"],
    relatedCompetencyIds: ["documentation-practices", "hiring-and-onboarding"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["LEADERSHIP", "COLLABORATION", "COMMUNICATION", "RESPONSIBILITY"],
    preferredEvidenceFamilies: ["LEADERSHIP_EXAMPLE", "INTERVIEW_STORY", "PROFESSIONAL_RESPONSIBILITY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "SUPPORTING"
  }),
  competency({
    id: "technical-leadership",
    name: "Technical Leadership",
    category: "LEADERSHIP",
    description: "Direct technical leadership and guidance.",
    aliases: ["technical leadership", "technical lead"],
    requirementSignals: ["technical leadership", "leadership"],
    evidenceSignals: ["led", "technical direction", "guided"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: ["architecture-influence", "technical-judgment", "mentoring"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: ["team-coordination"],
    allowedRequirementKinds: ["LEADERSHIP", "RESPONSIBILITY", "COLLABORATION", "OTHER"],
    preferredEvidenceFamilies: ["LEADERSHIP_EXAMPLE", "PROFESSIONAL_ACCOMPLISHMENT", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "team-coordination",
    name: "Team Coordination",
    category: "LEADERSHIP",
    description: "Coordinating work across a team or delivery stream.",
    aliases: ["team coordination", "coordinated teams"],
    requirementSignals: ["coordinate", "coordination"],
    evidenceSignals: ["coordinated", "organized delivery", "aligned teams"],
    technologySignals: [],
    parentCompetencyIds: ["technical-leadership"],
    relatedCompetencyIds: ["cross-functional-collaboration"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["LEADERSHIP", "COLLABORATION", "RESPONSIBILITY"],
    preferredEvidenceFamilies: ["LEADERSHIP_EXAMPLE", "PROFESSIONAL_RESPONSIBILITY", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "architecture-influence",
    name: "Architecture Influence",
    category: "LEADERSHIP",
    description: "Influencing architectural decisions across a broader scope.",
    aliases: ["architecture influence", "technical direction"],
    requirementSignals: ["architecture reviews", "architecture influence"],
    evidenceSignals: ["architecture decisions", "technical direction"],
    technologySignals: [],
    parentCompetencyIds: ["technical-leadership"],
    relatedCompetencyIds: ["system-design", "technical-judgment"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["LEADERSHIP", "ARCHITECTURE", "RESPONSIBILITY"],
    preferredEvidenceFamilies: ["LEADERSHIP_EXAMPLE", "ARCHITECTURE_EXAMPLE", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "hiring-and-onboarding",
    name: "Hiring and Onboarding",
    category: "LEADERSHIP",
    description: "Hiring, interviewing, and onboarding support.",
    aliases: ["hiring", "onboarding", "interviewing"],
    requirementSignals: ["hiring", "onboarding"],
    evidenceSignals: ["hiring", "onboarded", "interviewed"],
    technologySignals: [],
    parentCompetencyIds: ["mentoring"],
    relatedCompetencyIds: ["knowledge-sharing"],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["LEADERSHIP", "COLLABORATION", "RESPONSIBILITY"],
    preferredEvidenceFamilies: ["LEADERSHIP_EXAMPLE", "INTERVIEW_STORY"],
    disallowedEvidenceFamilies: ["PROFESSIONAL_ROLE"],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "domain-finance",
    name: "Finance Domain",
    category: "DOMAIN",
    description: "Finance, fintech, banking, or related domain context.",
    aliases: ["finance", "financial", "banking", "fintech"],
    requirementSignals: ["finance", "financial", "banking", "fintech"],
    evidenceSignals: ["finance", "financial", "banking", "fintech"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: [],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["DOMAIN"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ROLE", "PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "domain-healthcare",
    name: "Healthcare Domain",
    category: "DOMAIN",
    description: "Healthcare or medical domain context.",
    aliases: ["healthcare", "health care", "medical"],
    requirementSignals: ["healthcare", "medical"],
    evidenceSignals: ["healthcare", "medical"],
    technologySignals: [],
    parentCompetencyIds: [],
    relatedCompetencyIds: [],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["DOMAIN"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ROLE", "PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  }),
  competency({
    id: "domain-compliance",
    name: "Compliance Domain",
    category: "DOMAIN",
    description: "Compliance, audit, or regulated-work domain context.",
    aliases: ["compliance", "audit", "assurance", "regulated"],
    requirementSignals: ["compliance", "audit", "assurance", "regulated"],
    evidenceSignals: ["compliance", "audit", "assurance", "regulated"],
    technologySignals: ["SOC 2", "FedRAMP"],
    parentCompetencyIds: [],
    relatedCompetencyIds: [],
    stronglyImpliedCompetencyIds: [],
    weaklyRelatedCompetencyIds: [],
    allowedRequirementKinds: ["DOMAIN", "SECURITY"],
    preferredEvidenceFamilies: ["PROFESSIONAL_ROLE", "PROFESSIONAL_ACCOMPLISHMENT", "PROFESSIONAL_RESPONSIBILITY"],
    disallowedEvidenceFamilies: [],
    minimumRelationshipStrength: "DIRECT"
  })
];

export const competencyCatalog: CompetencyCatalog = {
  contractVersion: COMPETENCY_CATALOG_CONTRACT_VERSION,
  catalogVersion: COMPETENCY_CATALOG_VERSION,
  competencies
};
